In [162]:
import pandas as pd
import numpy as np
from ast import literal_eval
import re

In [163]:
pd.set_option('display.max_columns', None)

In [164]:
ruta=("C:\\Users\\LENOVO\\Desktop\\Jacobo\\DATOS PISOS\\PROYECTO FINAL\\ALQUILER\\datos_unificados_alquiler.csv")
datos_alquiler = pd.read_csv(ruta, encoding='utf-16', sep=';', converters={'caracteristicas_basicas': literal_eval, 'caracteristicas_extra': literal_eval, 'ubicacion': literal_eval})
datos_alquiler.head(10)

,id,titulo,localización,precio,caracteristicas_basicas,caracteristicas_extra,ubicacion
0,108649983,"Alquiler de piso en calle de Juanelo, 23",Lavapiés-Embajadores,1300,"[47 m² construidos, 1 habitación, 1 baño, Segu...","[Aire acondicionado, Consumo: \n227 kWh/m² año...","[Calle de Juanelo, 23, Barrio Lavapiés-Embajad..."
1,100086672,Alquiler de piso en Vicente Ferrer,Malasaña-Universidad,1350,"[60 m² construidos, 40 m² útiles, 1 habitación...","[Aire acondicionado, Consumo:, Emisiones:]","[Vicente Ferrer, Barrio Malasaña-Universidad, ..."
2,105407203,"Alquiler de piso en calle de las Aguas, 8",Palacio,2000,"[98 m² construidos, 90 m² útiles, 3 habitacion...","[Aire acondicionado, En trámite]","[Calle de las Aguas, 8, Barrio Palacio, Distri..."
3,99564765,Alquiler de piso en travesía de Trujillos,Sol,1580,"[50 m² construidos, 45 m² útiles, 1 habitación...","[Aire acondicionado, Consumo:, Emisiones:]","[Travesía de Trujillos, Barrio Sol, Distrito C..."
4,108651419,"Alquiler de piso en calle de Lavapiés, 40",Lavapiés-Embajadores,1850,"[85 m² construidos, 3 habitaciones, 1 baño, Ba...","[Consumo:, Emisiones:]","[Calle de Lavapiés, 40, Barrio Lavapiés-Embaja..."
5,92863859,Alquiler de piso en calle Jesus Del Valle,Malasaña-Universidad,1650,"[75 m² construidos, 70 m² útiles, 2 habitacion...","[Consumo:, Emisiones:]","[Calle JESUS DEL VALLE, Barrio Malasaña-Univer..."
6,108640831,"Alquiler de estudio en Gran Vía, 78",Malasaña-Universidad,1164,"[45 m² construidos, 40 m² útiles, Sin habitaci...",[En trámite],"[Gran Vía, 78, Barrio Malasaña-Universidad, Di..."
7,102207245,Alquiler de estudio en calle de Hernán Cortés,Chueca-Justicia,1111,"[51 m² construidos, Sin habitación, 1 baño, Ba...","[Aire acondicionado, No indicado]","[Calle de Hernán Cortés, Barrio Chueca-Justici..."
8,108649900,"Alquiler de piso en calle del Amparo, 84",Lavapiés-Embajadores,2500,"[79 m² construidos, 75 m² útiles, 4 habitacion...",[En trámite],"[Calle del Amparo, 84, Barrio Lavapiés-Embajad..."
9,108265632,Alquiler de piso en calle de Buenavista,Lavapiés-Embajadores,1275,"[40 m² construidos, 2 habitaciones, 1 baño, Se...","[Aire acondicionado, En trámite]","[Calle de Buenavista, Barrio Lavapiés-Embajado..."

In [165]:
datos_alquiler.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7442 entries, 0 to 7441
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       7442 non-null   int64
 1   titulo                   7442 non-null   object
 2   localización             7442 non-null   object
 3   precio                   7442 non-null   int64
 4   caracteristicas_basicas  7442 non-null   object
 5   caracteristicas_extra    7442 non-null   object
 6   ubicacion                7442 non-null   object
dtypes: int64(2), object(5)
memory usage: 407.1+ KB

## funciones de deteccionde los diferentes datos

In [166]:
def match_property(property, patterns):
    for pat in patterns:
        match_prop = re.search(pat, property)
        if match_prop:
            return True
    return False

In [167]:
def get_number(property):
    nums = re.findall(r'\d+', property)
    if len(nums) >= 2:
        return int(nums[0] + nums[1])  # Une dos números como texto, luego convierte
    elif len(nums) == 1:
        return int(nums[0])
    else:
        return 0

In [168]:
def check_property(property, patterns):
    for pat in patterns:
        check = re.search(pat, property)
        if check:
            return 1
    return 0

## funciones para sacar la información en columnas nuevas

In [169]:
def get_baños(features):
    for prop in features:
        if match_property(prop.lower().strip(), ['baño']):
            return(get_number(prop.lower().strip()))

In [170]:
get_number('2 baños')

2

In [171]:
def get_ascensor(features):
    for prop in features:
        if match_property(prop.lower().strip(), ['ascensor']):
            return(check_property(prop.lower().strip(),['con'] ))

In [172]:
def get_años(features):
    for prop in features:
        if match_property(prop.lower().strip(), ['construido en']):
            return(get_number(prop.lower().strip()))

In [173]:
def get_terraza(features):
    value = 0
    for prop in features:
        if match_property(prop.lower().strip(), ['terraza']):
            value +=1
    return(value)

In [174]:
def get_trastero(features):
    value = 0
    for prop in features:
        if match_property(prop.lower().strip(), ['trastero']):
            value +=1
    return(value)

In [175]:
def get_orientacion(features):
    for prop in features:
        if match_property(prop.lower().strip(), ['orientación']):
            return(prop.split(' ', maxsplit=1)[1].strip().strip(', '[0]))

In [176]:
def get_piso(features):
    for prop in features:
        if match_property(prop.lower().strip(), ['bajo', 'planta', 'interior', 'exterior']):
            return(prop)

In [177]:
def get_habitaciones(features):
    for prop in features:
        if match_property(prop.lower().strip(), ['habitaci']):
            try:
                habitaciones = get_number(prop.lower().strip())
            except:
                habitaciones = prop
            return(habitaciones)

In [178]:
def get_metros_2(features):
    for prop in features:
        if match_property(prop.lower().strip(), ['m² construidos']):
            try:
                metros = get_number(prop.lower().strip().split(',')[0])
            except:
                metros = prop
            return(metros)

In [179]:
def get_condicion(features):
    for prop in features:
        if match_property(prop.lower().strip(), ['segunda mano', 'promocion de obra nueva']):
            return(prop)

In [180]:
def get_balcon(features):
    value = 0
    for prop in features:
        if match_property(prop.lower().strip(), ['balcón']):
            value +=1
    return(value)

In [181]:
def get_armario_empotrado(features):
    value = 0
    for prop in features:
        if match_property(prop.lower().strip(), ['armarios empotrados']):
            value +=1
    return(value)

In [182]:
def get_jardin(features):
    value = 0
    for prop in features:
        if match_property(prop.lower().strip(), ['jardin']):
            value +=1
    return(value)

In [183]:
def get_garaje(features):
    value = 0
    for prop in features:
        if match_property(prop.lower().strip(), ['garaje']):
            value +=1
    return(value)

In [184]:
def get_calefaccion(features):
    value = 0
    for prop in features:
        if match_property(prop.lower().strip(), ['calefacción']):
            value +=1
    return(value)

In [185]:
def get_aire_acon(features):
    value = 0
    for prop in features:
        if match_property(prop.lower().strip(), ['aire acondicionados']):
            value +=1
    return(value)

In [186]:
def extraer_consumo(x):
    if isinstance(x, list):
        x = " ".join(x)
    match = re.search(r'Consumo:\s*\\?n?\s*(\d+)', str(x))
    return int(match.group(1)) if match else None

In [187]:
def extraer_emisiones(x):
    if isinstance(x, list):
        x = " ".join(x)
    match = re.search(r'Emisiones:\s*\\?n?\s*(\d+)', str(x))
    return int(match.group(1)) if match else None

In [188]:
datos_alquiler['m2'] = datos_alquiler.caracteristicas_basicas.apply(get_metros_2)
datos_alquiler['habitaciones'] = datos_alquiler.caracteristicas_basicas.apply(get_habitaciones)
datos_alquiler['baño'] = datos_alquiler.caracteristicas_basicas.apply(get_baños)
datos_alquiler['terraza'] = datos_alquiler.caracteristicas_basicas.apply(get_terraza)
datos_alquiler['estado'] = datos_alquiler.caracteristicas_basicas.apply(get_condicion)
datos_alquiler['armarios'] = datos_alquiler.caracteristicas_basicas.apply(get_armario_empotrado)
datos_alquiler['orientacion'] = datos_alquiler.caracteristicas_basicas.apply(get_orientacion)
datos_alquiler['construido'] = datos_alquiler.caracteristicas_basicas.apply(get_años)
datos_alquiler['calefaccion'] = datos_alquiler.caracteristicas_basicas.apply(get_calefaccion)
datos_alquiler['ascensor'] = datos_alquiler.caracteristicas_basicas.apply(get_ascensor)
datos_alquiler['garaje'] = datos_alquiler.caracteristicas_basicas.apply(get_garaje)
datos_alquiler['trastero'] = datos_alquiler.caracteristicas_basicas.apply(get_trastero)
datos_alquiler['planta'] = datos_alquiler.caracteristicas_basicas.apply(get_piso)
datos_alquiler['balcon'] = datos_alquiler.caracteristicas_basicas.apply(get_balcon)
datos_alquiler['jardin'] = datos_alquiler.caracteristicas_basicas.apply(get_jardin)
datos_alquiler['aire acondicionado'] = datos_alquiler.caracteristicas_extra.apply(get_aire_acon)
datos_alquiler['consumo_kWh'] = datos_alquiler['caracteristicas_extra'].apply(extraer_consumo)
datos_alquiler['emisiones_CO2'] = datos_alquiler['caracteristicas_extra'].apply(extraer_emisiones)

In [189]:
datos_alquiler.head(5)

,id,titulo,localización,precio,caracteristicas_basicas,caracteristicas_extra,ubicacion,m2,habitaciones,baño,terraza,estado,armarios,orientacion,construido,calefaccion,ascensor,garaje,trastero,planta,balcon,jardin,aire acondicionado,consumo_kWh,emisiones_CO2
0,108649983,"Alquiler de piso en calle de Juanelo, 23",Lavapiés-Embajadores,1300,"[47 m² construidos, 1 habitación, 1 baño, Segu...","[Aire acondicionado, Consumo: \n227 kWh/m² año...","[Calle de Juanelo, 23, Barrio Lavapiés-Embajad...",47,1,1,0,Segunda mano/buen estado,1,"sur, este",NaN,0,None,0,0,None,0,0,0,227.0,40.0
1,100086672,Alquiler de piso en Vicente Ferrer,Malasaña-Universidad,1350,"[60 m² construidos, 40 m² útiles, 1 habitación...","[Aire acondicionado, Consumo:, Emisiones:]","[Vicente Ferrer, Barrio Malasaña-Universidad, ...",60,1,1,0,Segunda mano/buen estado,1,"este, oeste",NaN,1,None,0,0,None,0,0,0,NaN,NaN
2,105407203,"Alquiler de piso en calle de las Aguas, 8",Palacio,2000,"[98 m² construidos, 90 m² útiles, 3 habitacion...","[Aire acondicionado, En trámite]","[Calle de las Aguas, 8, Barrio Palacio, Distri...",98,3,1,0,Segunda mano/buen estado,0,None,NaN,0,None,0,0,None,1,0,0,NaN,NaN
3,99564765,Alquiler de piso en travesía de Trujillos,Sol,1580,"[50 m² construidos, 45 m² útiles, 1 habitación...","[Aire acondicionado, Consumo:, Emisiones:]","[Travesía de Trujillos, Barrio Sol, Distrito C...",50,1,1,0,Segunda mano/buen estado,1,"sur, oeste",NaN,1,None,0,0,None,1,0,0,NaN,NaN
4,108651419,"Alquiler de piso en calle de Lavapiés, 40",Lavapiés-Embajadores,1850,"[85 m² construidos, 3 habitaciones, 1 baño, Ba...","[Consumo:, Emisiones:]","[Calle de Lavapiés, 40, Barrio Lavapiés-Embaja...",85,3,1,0,Segunda mano/buen estado,1,None,NaN,0,None,0,0,None,1,0,0,NaN,NaN

In [190]:
datos_alquiler.drop(columns=['caracteristicas_basicas', 'caracteristicas_extra'], inplace= True)

In [215]:
datos_alquiler["precio_m2"] = datos_alquiler["precio"] / datos_alquiler["m2"]

# Redondear si quieres
datos_alquiler["precio_m2"] = datos_alquiler["precio_m2"].round(2)

# Ver primeras filas
print(datos_alquiler[["precio", "m2", "precio_m2"]].head())

   precio  m2  precio_m2
0    1300  47      27.66
1    1350  60      22.50
2    2000  98      20.41
3    1580  50      31.60
4    1850  85      21.76

In [216]:
datos_alquiler.head(5)

,precio,m2,habitaciones,baños,terraza,estado,armarios,calefaccion,garaje,trastero,aire acondicionado,vivienda,ciudad,distrito,barrio,precio_m2
0,1300,47,1,1,0,Segunda mano/buen estado,1,0,0,0,0,piso,Madrid,Centro,Lavapiés-Embajadores,27.66
1,1350,60,1,1,0,Segunda mano/buen estado,1,1,0,0,0,piso,Madrid,Centro,Malasaña-Universidad,22.50
2,2000,98,3,1,0,Segunda mano/buen estado,0,0,0,0,0,piso,Madrid,Centro,Palacio,20.41
3,1580,50,1,1,0,Segunda mano/buen estado,1,1,0,0,0,piso,Madrid,Centro,Sol,31.60
4,1850,85,3,1,0,Segunda mano/buen estado,1,0,0,0,0,piso,Madrid,Centro,Lavapiés-Embajadores,21.76

In [192]:
datos_alquiler['vivienda'] = datos_alquiler['titulo'].apply(lambda x: str(x).split()[2] if pd.notnull(x) and len(str(x).split()) > 0 else None)

# EDA

In [193]:
datos_alquiler.head(5)

,id,titulo,localización,precio,ubicacion,m2,habitaciones,baño,terraza,estado,armarios,orientacion,construido,calefaccion,ascensor,garaje,trastero,planta,balcon,jardin,aire acondicionado,consumo_kWh,emisiones_CO2,vivienda
0,108649983,"Alquiler de piso en calle de Juanelo, 23",Lavapiés-Embajadores,1300,"[Calle de Juanelo, 23, Barrio Lavapiés-Embajad...",47,1,1,0,Segunda mano/buen estado,1,"sur, este",NaN,0,None,0,0,None,0,0,0,227.0,40.0,piso
1,100086672,Alquiler de piso en Vicente Ferrer,Malasaña-Universidad,1350,"[Vicente Ferrer, Barrio Malasaña-Universidad, ...",60,1,1,0,Segunda mano/buen estado,1,"este, oeste",NaN,1,None,0,0,None,0,0,0,NaN,NaN,piso
2,105407203,"Alquiler de piso en calle de las Aguas, 8",Palacio,2000,"[Calle de las Aguas, 8, Barrio Palacio, Distri...",98,3,1,0,Segunda mano/buen estado,0,None,NaN,0,None,0,0,None,1,0,0,NaN,NaN,piso
3,99564765,Alquiler de piso en travesía de Trujillos,Sol,1580,"[Travesía de Trujillos, Barrio Sol, Distrito C...",50,1,1,0,Segunda mano/buen estado,1,"sur, oeste",NaN,1,None,0,0,None,1,0,0,NaN,NaN,piso
4,108651419,"Alquiler de piso en calle de Lavapiés, 40",Lavapiés-Embajadores,1850,"[Calle de Lavapiés, 40, Barrio Lavapiés-Embaja...",85,3,1,0,Segunda mano/buen estado,1,None,NaN,0,None,0,0,None,1,0,0,NaN,NaN,piso

In [194]:
datos_alquiler["vivienda"].unique()

array(['piso', 'estudio', 'ático', 'dúplex', 'casa', 'chalet'],
      dtype=object)

In [195]:
datos_alquiler.drop(columns=['id', 'titulo', 'localización', 'orientacion', 'construido', 'balcon', 'jardin' ], inplace= True)

In [196]:
datos_alquiler.drop(columns=['consumo_kWh', 'emisiones_CO2'], inplace= True)

In [197]:
datos_alquiler.drop(columns=['ascensor', 'planta'], inplace= True)

In [198]:
datos_alquiler.shape

(7442, 13)

In [199]:
datos_alquiler.isnull().sum()

precio                 0
ubicacion              0
m2                     0
habitaciones           0
baño                   0
terraza                0
estado                27
armarios               0
calefaccion            0
garaje                 0
trastero               0
aire acondicionado     0
vivienda               0
dtype: int64

In [200]:
print(datos_alquiler["ubicacion"].head(20).tolist())

[['Calle de Juanelo, 23', 'Barrio Lavapiés-Embajadores', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Vicente Ferrer', 'Barrio Malasaña-Universidad', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle de las Aguas, 8', 'Barrio Palacio', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Travesía de Trujillos', 'Barrio Sol', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle de Lavapiés, 40', 'Barrio Lavapiés-Embajadores', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle JESUS DEL VALLE', 'Barrio Malasaña-Universidad', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Gran Vía, 78', 'Barrio Malasaña-Universidad', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle de Hernán Cortés', 'Barrio Chueca-Justicia', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle del Amparo, 84', 'Barrio Lavapiés-Embajadores', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle de Buenavista', 'Barrio Lavapiés-Embajadores', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle del Carnero, 16', 'Barrio Lavapiés-Embajadores', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle del Príncipe', 'Barrio Huertas-Cortes', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle de la Palma', 'Barrio Malasaña-Universidad', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle de Pelayo', 'Barrio Chueca-Justicia', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle del Humilladero', 'Barrio Palacio', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle del Limón, 32', 'Barrio Malasaña-Universidad', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle del Caballero de Gracia', 'Barrio Sol', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle de las Tres Cruces', 'Barrio Sol', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Plaza de Carlos Cambronero, 4', 'Barrio Malasaña-Universidad', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle del Príncipe', 'Barrio Huertas-Cortes', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid']]

In [201]:
datos_alquiler["ubicacion"] = datos_alquiler["ubicacion"].astype(str)

In [202]:
datos_alquiler["ciudad"]   = datos_alquiler["ubicacion"].str.split(",").str[-3].str.strip()
datos_alquiler["distrito"] = datos_alquiler["ubicacion"].str.split(",").str[-4].str.strip()
datos_alquiler["barrio"]   = datos_alquiler["ubicacion"].str.split(",").str[-5].str.strip()

In [203]:
datos_alquiler.head(5)

,precio,ubicacion,m2,habitaciones,baño,terraza,estado,armarios,calefaccion,garaje,trastero,aire acondicionado,vivienda,ciudad,distrito,barrio
0,1300,"['Calle de Juanelo, 23', 'Barrio Lavapiés-Emba...",47,1,1,0,Segunda mano/buen estado,1,0,0,0,0,piso,'Madrid','Distrito Centro','Barrio Lavapiés-Embajadores'
1,1350,"['Vicente Ferrer', 'Barrio Malasaña-Universida...",60,1,1,0,Segunda mano/buen estado,1,1,0,0,0,piso,'Madrid','Distrito Centro','Barrio Malasaña-Universidad'
2,2000,"['Calle de las Aguas, 8', 'Barrio Palacio', 'D...",98,3,1,0,Segunda mano/buen estado,0,0,0,0,0,piso,'Madrid','Distrito Centro','Barrio Palacio'
3,1580,"['Travesía de Trujillos', 'Barrio Sol', 'Distr...",50,1,1,0,Segunda mano/buen estado,1,1,0,0,0,piso,'Madrid','Distrito Centro','Barrio Sol'
4,1850,"['Calle de Lavapiés, 40', 'Barrio Lavapiés-Emb...",85,3,1,0,Segunda mano/buen estado,1,0,0,0,0,piso,'Madrid','Distrito Centro','Barrio Lavapiés-Embajadores'

In [204]:
datos_alquiler["ciudad"].unique()

array(["'Madrid'", "'Majadahonda'", "'Pozuelo de Alarcón'",
       "'Las Rozas de Madrid'", "'Collado Villalba'",
       "'Villanueva de la Cañada'", "['Distrito Villanueva de la Cañada'",
       "'Paracuellos de Jarama'", "'La Moraleja'", "'Pedrezuela'",
       "'San Sebastián de los Reyes'", "'Alcobendas'",
       "'Valdetorres de Jarama'", "'Colmenar Viejo'", "'Tres Cantos'",
       "'Ciudalcampo'", "'Talamanca de Jarama'", nan,
       "'San Agustin de Guadalix'", "'Fuente el Saz de Jarama'",
       "'Miraflores de la Sierra'", "'Club de Campo'",
       "'Buitrago del Lozoya'", "'Valdelagua'", "'Cobeña'",
       "'Fuente del Fresno'", "'Santo Domingo'", "'Venturada'",
       "'Cotos de Monterrey'", "'Guadalix de la Sierra'", "'Algete'",
       "'Ajalvir'", "'Valdeavero'", "'El Molar'",
       "'Valdeolmos-Alalpardo'", "'Valdemanco'", "'El Vellón'",
       "'Manzanares el Real'", "'Soto del Real'", "'Puebla de la Sierra'",
       "'La Cabrera'", "'Torrelaguna'", "'Bustarviejo'"], dtype=object)

In [205]:
datos_alquiler.drop(columns=['ubicacion'], inplace= True)

In [206]:
datos_alquiler.head(5)

,precio,m2,habitaciones,baño,terraza,estado,armarios,calefaccion,garaje,trastero,aire acondicionado,vivienda,ciudad,distrito,barrio
0,1300,47,1,1,0,Segunda mano/buen estado,1,0,0,0,0,piso,'Madrid','Distrito Centro','Barrio Lavapiés-Embajadores'
1,1350,60,1,1,0,Segunda mano/buen estado,1,1,0,0,0,piso,'Madrid','Distrito Centro','Barrio Malasaña-Universidad'
2,2000,98,3,1,0,Segunda mano/buen estado,0,0,0,0,0,piso,'Madrid','Distrito Centro','Barrio Palacio'
3,1580,50,1,1,0,Segunda mano/buen estado,1,1,0,0,0,piso,'Madrid','Distrito Centro','Barrio Sol'
4,1850,85,3,1,0,Segunda mano/buen estado,1,0,0,0,0,piso,'Madrid','Distrito Centro','Barrio Lavapiés-Embajadores'

In [207]:
datos_alquiler["distrito"] = (
    datos_alquiler["distrito"]
    .astype(str)                          # asegurar que es texto
    .str.replace("'", "", regex=False)    # eliminar comillas simples
    .str.strip()                          # quitar espacios extra
)
datos_alquiler["barrio"] = (
    datos_alquiler["barrio"]
    .astype(str)                          # asegurar que es texto
    .str.replace("'", "", regex=False)    # eliminar comillas simples
    .str.strip()                          # quitar espacios extra
)

datos_alquiler["ciudad"] = (
    datos_alquiler["ciudad"]
    .astype(str)                          # asegurar que es texto
    .str.replace("'", "", regex=False)    # eliminar comillas simples
    .str.strip()                          # quitar espacios extra
)

In [208]:

datos_alquiler["distrito"] = (
    datos_alquiler["distrito"]
    .astype(str)
    .str.split(" ", n=1)   # separa en 2 partes: primera palabra + resto
    .str[1]                # se queda con la segunda parte
    .str.strip())

In [209]:
datos_alquiler["barrio"] = (
    datos_alquiler["barrio"]
    .astype(str)
    .str.split(" ", n=1)   # separa en 2 partes: primera palabra + resto
    .str[1]                # se queda con la segunda parte
    .str.strip())

In [210]:
datos_alquiler["ciudad"].unique()

array(['Madrid', 'Majadahonda', 'Pozuelo de Alarcón',
       'Las Rozas de Madrid', 'Collado Villalba',
       'Villanueva de la Cañada', '[Distrito Villanueva de la Cañada',
       'Paracuellos de Jarama', 'La Moraleja', 'Pedrezuela',
       'San Sebastián de los Reyes', 'Alcobendas',
       'Valdetorres de Jarama', 'Colmenar Viejo', 'Tres Cantos',
       'Ciudalcampo', 'Talamanca de Jarama', 'nan',
       'San Agustin de Guadalix', 'Fuente el Saz de Jarama',
       'Miraflores de la Sierra', 'Club de Campo', 'Buitrago del Lozoya',
       'Valdelagua', 'Cobeña', 'Fuente del Fresno', 'Santo Domingo',
       'Venturada', 'Cotos de Monterrey', 'Guadalix de la Sierra',
       'Algete', 'Ajalvir', 'Valdeavero', 'El Molar',
       'Valdeolmos-Alalpardo', 'Valdemanco', 'El Vellón',
       'Manzanares el Real', 'Soto del Real', 'Puebla de la Sierra',
       'La Cabrera', 'Torrelaguna', 'Bustarviejo'], dtype=object)

In [211]:
datos_alquiler.rename(columns={"baño": "baños"}, inplace=True)

In [212]:
datos_alquiler.to_csv("datos_alquiler.csv", index=False, sep=";")

In [213]:
datos_alquiler.head(5)

,precio,m2,habitaciones,baños,terraza,estado,armarios,calefaccion,garaje,trastero,aire acondicionado,vivienda,ciudad,distrito,barrio
0,1300,47,1,1,0,Segunda mano/buen estado,1,0,0,0,0,piso,Madrid,Centro,Lavapiés-Embajadores
1,1350,60,1,1,0,Segunda mano/buen estado,1,1,0,0,0,piso,Madrid,Centro,Malasaña-Universidad
2,2000,98,3,1,0,Segunda mano/buen estado,0,0,0,0,0,piso,Madrid,Centro,Palacio
3,1580,50,1,1,0,Segunda mano/buen estado,1,1,0,0,0,piso,Madrid,Centro,Sol
4,1850,85,3,1,0,Segunda mano/buen estado,1,0,0,0,0,piso,Madrid,Centro,Lavapiés-Embajadores